services:
  locust:
    image: python:3.13-slim

    container_name: locust

    working_dir: /mnt/locust

    volumes:
      - .:/mnt/locust

    ports:
      - "8089:8089"

    command: >
      sh -c "
      pip install -r requirements.txt &&
      locust -f locustfile.py
      "